# Generated by Django 4.1.5 on 2023-05-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='prenom',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
