# Generated by Django 4.1.5 on 2023-05-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0002_transactions_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='prenom',
        ),
    ]
